# coding=utf-8

# 开启DEBUG模式
DEBUG = True

# 工程密钥
SECRET_KEY = b'****'

# Mysql数据库
HOST = '127.0.0.1'
PORT = '3306'
USERNAME = '***'
PASSWORD = '***'
DB_NAME = '***'

DB_URI = 'mysql+pymysql://{user}:{pwd}@{host}:{port}/{database}?charset=utf8'.format(
    user=USERNAME, pwd=PASSWORD, host=HOST, port=PORT, database=DB_NAME
)

SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True

# CMSsession Key
CMS_USER_SESSION = ''
FRONT_USER_SESSION = ''

# Send E-mail
MAIL_SERVER = '***'
MAIL_PORT = 25
MAIL_USERNAME = ''
MAIL_PASSWORD = ''
MAIL_DEFAULT_SENDER = ''

# Captcha 位数
CAPTCHA_NUM = 6

# 阿里大于短信
ACCESS_KEY_ID = "***"
ACCESS_KEY_SECRET = ""
SIGN_NAME = ''
TEMPLATE_CODE = ''

# 七牛
QINIU_ACCESS_KEY = ''
QINIU_SECRET_KEY = '_XvtKMz-****'
QINIU_BUCKET = '***-bbs'

# Ueditor
UEDITOR_UPLOAD_TO_QINIU = True
UEDITOR_QINIU_ACCESS_KEY = QINIU_ACCESS_KEY
UEDITOR_QINIU_SECRET_KEY = QINIU_SECRET_KEY
UEDITOR_QINIU_BUCKET_NAME = QINIU_BUCKET
UEDITOR_QINIU_DOMAIN = ""

# flask-paginate
PER_PAGE = 12
POST_PER_PAGE = 15

# celery
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/1'
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/1'
